### ISSUE TITLE
Feed in custom language content

### ISSUE THREAD

**Issue by Garbee** [WICG/translation-api#6]
Perhaps more long-term to build, but worth discussing early to keep in mind. It would be excellent to have the ability for a site to load in our custom translation data. That way we could not necessarily rely on “whatever the browser does” for legal reasons. Instead opting to leverage the same API after loading in custom content for our domain/page load. Then our content would be prioritized, following any browser assistance if desired.

Some apps have the need for translation, but we can’t rely on things done “automatically”. It could be a huge simplification to frameworks to not need to provide translation support in them unless they have a special need, like static builds per-language in Angular. So long as runtime operations fit the app’s need, this API could be used to handle the conversions on the client.

Is this something that has been considered already? Would it ever fit in line with what user agents could allow?

**Comment by domenic** [comment]
I'm a little unclear what you're proposing here. Since this is a browser API, by design it's going to do "whatever the browser does". Whereas, if you want to do your own translation without the browser being involved, then probably you won't use this API; you'll just include your own translations.

Perhaps you could give a code sample of what you're thinking, and contrast it with the current code samples in the readme?
